# YAML pipeline for Python project in GitHub

name: Python Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: Code/Nausicaa.Green.Initiative.Backend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.7'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r packages.txt

    - name:
        python -m coverage run -m pytest
        python -m coverage report 
