name: Angular Image

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
      branch:
        description: Branch to trigger build on
        default: develop
        required: true
        type: choice
        options:
        - develop
        - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Angular Image
    defaults: 
      run:
        working-directory: Code/Nausicaa.Green.Initiative.UI/global-green-initiative
  
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 16.14.2
        
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: List Files/Folders
      run: |
        find .
        
    - name: Install Angular
      #if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: |
        npm ci
        
    - name: Build Angular
      run: |
        npm run ng build --configuration=production
        
    #- name: Test
      #run: |
      #  npm run test --configuration=production
      
    - name: Docker Login
      run: docker login -u tonymathewt -p ${{ secrets.dockerlogin }}
      
    - name: Docker build
      run: docker build -t nausicaa:v1 --force-rm .
      
    - name: Docker Tag
      run: docker tag nausicaa:v1 tonymathewt/nausicaa:v3
      
    - name: Docker Push
      run: docker push tonymathewt/nausicaa:v3
